package com.devharnesskit.dhk.command;

import com.devharnesskit.dhk.cli.Args;
import com.devharnesskit.dhk.cli.Command;
import com.devharnesskit.dhk.cli.CommandContext;
import com.devharnesskit.dhk.cli.ExitCodes;

public final class HelpCommand implements Command {
    public int run(CommandContext context, Args args) {
        context.out().println("DevHarness Kit CLI (dhk)");
        context.out().println();
        context.out().println("Usage:");
        context.out().println("  dhk help");
        context.out().println("  dhk version");
        context.out().println("  dhk doctor --project-root <path>");
        context.out().println("  dhk memory init --project-root <path>");
        context.out().println("  dhk memory add --type <type> --title <title> --content <content>|--content-file <path>|--content-stdin");
        context.out().println("  dhk memory confirm --id <id>");
        context.out().println("  dhk memory search --q <query> [--explain]");
        context.out().println("  dhk memory export --task <task>");
        context.out().println("  dhk memory checkpoint --task <task> --summary <summary>|--summary-file <path>|--summary-stdin");
        context.out().println("  dhk memory recover --latest");
        context.out().println("  dhk memory backup [--out <path>]");
        context.out().println("  dhk db test --jdbc-url <url> --user <user> --password-env <env>");
        context.out().println("  dhk db test --host <host> --database <db> [--server-timezone <zone>]");
        context.out().println("  dhk db sql --sql <sql>|--sql-file <path>|--sql-stdin --password-env <env>");
        context.out().println("  dhk goal start --profile <profile> --task <task> [--module <module>] [--mode <mode>]");
        context.out().println("  dhk goal resume [--goal <goal-key>]");
        context.out().println("  dhk goal next [--goal <goal-key>]");
        context.out().println("  dhk goal step --goal <goal-key> --summary <summary> [--changed-files <files>] [--evidence <evidence>]");
        context.out().println("  dhk goal check [--goal <goal-key>] --check <check-key>|--all");
        context.out().println("  dhk goal evaluate [--goal <goal-key>]");
        context.out().println("  dhk goal verify [--goal <goal-key>]");
        context.out().println("  dhk goal complete [--goal <goal-key>]");
        context.out().println("  dhk goal status [--goal <goal-key>]");
        context.out().println("  dhk goal export [--goal <goal-key>]");
        context.out().println("  dhk workflow template seed --project-root <path>");
        context.out().println("  dhk workflow template list --project-root <path>");
        context.out().println("  dhk workflow template show --key <workflow>");
        context.out().println("  dhk workflow start --workflow <workflow> --task <task>");
        context.out().println("  dhk workflow status --run <run-key>");
        context.out().println("  dhk workflow phase pass|fail --run <run-key> --phase <phase>");
        context.out().println("  dhk workflow gate pass|fail|waive --run <run-key> [--phase <phase>] --gate <gate>");
        context.out().println("  dhk workflow export --run <run-key>");
        context.out().println("  dhk workflow artifact list --run <run-key>");
        context.out().println("  dhk workflow bind-memory --run <run-key> --memory-id <id>");
        context.out().println("  dhk workflow bind-checkpoint --run <run-key> --checkpoint <id>");
        context.out().println("  dhk workflow summary --run <run-key>");
        context.out().println("  dhk spec create --change <key> --title <title>");
        context.out().println("  dhk spec document set --change <key> --type <type> --content <text>|--content-file <path>|--content-stdin");
        context.out().println("  dhk spec task add|update --change <key> --task <task>");
        context.out().println("  dhk spec acceptance add|update --change <key> --acceptance <acceptance>");
        context.out().println("  dhk spec status --change <key>");
        context.out().println("  dhk spec export --change <key>");
        context.out().println("  dhk spec bind-workflow --change <key> --run <run-key>");
        context.out().println("  dhk spec archive --change <key> --reason <reason>");
        context.out().println();
        context.out().println("Sensitive policy:");
        context.out().println("  .agents/devharness/sensitive-policy.json can set pattern actions to reject, redact, or allow.");
        context.out().println("Goal configuration:");
        context.out().println("  .agents/devharness/goal-profiles/*.json can override or add goal profiles.");
        context.out().println("  .agents/devharness/goal-check-policy.json can configure required goal checks.");
        context.out().println("Machine-readable output:");
        context.out().println("  Supported commands accept --json for alpha JSON output.");
        context.out().println("  dhk db sql also supports --format json for query results.");
        context.out().println();
        context.out().println("Exit codes:");
        context.out().println("  0 success");
        context.out().println("  1 runtime error");
        context.out().println("  2 usage error");
        context.out().println("  3 validation or safety rejection");
        context.out().println("  4 target not found");
        return ExitCodes.SUCCESS;
    }
}
