package com.devharnesskit.dhk.command;

import com.devharnesskit.dhk.cli.Args;
import com.devharnesskit.dhk.cli.Command;
import com.devharnesskit.dhk.cli.CommandContext;
import com.devharnesskit.dhk.cli.ExitCodes;

public final class HelpCommand implements Command {
    public int run(CommandContext context, Args args) {
        context.out().println("DevHarness Kit CLI (dhk)");
        context.out().println();
        context.out().println("Usage:");
        context.out().println("  dhk help");
        context.out().println("  dhk version");
        context.out().println("  dhk doctor --project-root <path>");
        context.out().println("  dhk status --project-root <path> [--json|--markdown] [--write <path>] [--exit-code]");
        context.out().println("  dhk readiness --project-root <path> [--json|--markdown] [--write <path>] [--exit-code]");
        context.out().println("    status is the human read-only snapshot; readiness is the CI/release gate alias.");
        context.out().println("  dhk advise --project-root <path> --task <task> [--mode recommend|patch|standard|strict|ask|analyze-only]");
        context.out().println("    advise writes Work Brief for users and Agent Brief for mounted agents; it does not start a goal.");
        context.out().println("  dhk quickstart --project-root <path> --task <task> [--preset <preset>] [--mode recommend|patch|standard|strict|ask|analyze-only] [--resume-existing] [--dry-run]");
        context.out().println("  dhk completion bash|zsh|fish");
        context.out().println("  dhk memory init --project-root <path>");
        context.out().println("  dhk memory add --type <type> --title <title> --content <content>|--content-file <path>|--content-stdin");
        context.out().println("  dhk memory confirm --id <id>");
        context.out().println("  dhk memory list [--status confirmed|draft|deprecated|archived] [--module <module>] [--tag <tag>] [--limit <n>]");
        context.out().println("  dhk memory search --q <query> [--explain]");
        context.out().println("  dhk memory export --task <task>");
        context.out().println("  dhk memory checkpoint --task <task> --summary <summary>|--summary-file <path>|--summary-stdin");
        context.out().println("  dhk memory recover --latest");
        context.out().println("  dhk memory backup [--out <path>]");
        context.out().println("  dhk db test --jdbc-url <url> --user <user> --password-env <env>");
        context.out().println("  dhk db test --host <host> --database <db> [--server-timezone <zone>]");
        context.out().println("  dhk db sql --sql <sql>|--sql-file <path>|--sql-stdin --password-env <env>");
        context.out().println("  dhk goal start --profile <profile> --task <task> [--module <module>] [--mode <mode>] [--force-new]");
        context.out().println("  dhk goal resume [--goal <goal-key>]");
        context.out().println("  dhk goal next [--goal <goal-key>]");
        context.out().println("  dhk goal evidence-template --goal <goal-key>");
        context.out().println("  dhk goal step --goal <goal-key> --summary <summary> [--auto] [--changed-files <files>] [--evidence <evidence>]");
        context.out().println("  dhk goal check [--goal <goal-key>] --check <check-key>|--all");
        context.out().println("  dhk goal evaluate [--goal <goal-key>]");
        context.out().println("  dhk goal verify [--goal <goal-key>] [--level fast|standard|release] [--markdown]");
        context.out().println("  dhk goal audit [--goal <goal-key>]");
        context.out().println("  dhk goal recheck [--goal <goal-key>]");
        context.out().println("  dhk goal complete [--goal <goal-key>]");
        context.out().println("  dhk goal status [--goal <goal-key>]");
        context.out().println("  dhk goal export [--goal <goal-key>]");
        context.out().println("  dhk graph init --project-root <path>");
        context.out().println("  dhk graph doctor --project-root <path>");
        context.out().println("  dhk graph status --project-root <path>");
        context.out().println("  dhk graph index --project-root <path>");
        context.out().println("  dhk graph impact --file <path>|--symbol <name>|--sql-table <table>|--scenario <key> [--depth <n>]");
        context.out().println("  dhk graph impact ... --allow-stale --allow-stale-evidence <evidence>");
        context.out().println("  dhk graph export --project-root <path>");
        context.out().println("  dhk graph prune --keep <n> [--dry-run] --project-root <path>");
        context.out().println("  dhk configure init --preset <preset> [--compile auto|manual|disabled] [--test auto|manual|disabled] [--graph off|advisory|required] [--dry-run]");
        context.out().println("  dhk configure show --project-root <path>");
        context.out().println("  dhk configure doctor --project-root <path>");
        context.out().println("  dhk configure explain [--key <config-key>]");
        context.out().println("  dhk bdd init --project-root <path>");
        context.out().println("  dhk bdd add --feature <key> --title <title> --scenario <key> --scenario-title <title>");
        context.out().println("  dhk bdd scenario create --scenario <key> --title <title> [--given <text>] [--when <text>] [--then <text>]");
        context.out().println("  dhk bdd scenario list [--feature <key>]");
        context.out().println("  dhk bdd scenario show --scenario <key>");
        context.out().println("  dhk bdd list [--feature <key>]");
        context.out().println("  dhk bdd show --scenario <key>|--feature <key>");
        context.out().println("  dhk bdd export [--feature <key>]");
        context.out().println("  dhk bdd lint [--feature <key>]");
        context.out().println("  dhk bdd evidence add --scenario <key> --summary <text> [--evidence-path <path>]");
        context.out().println("  dhk bdd evidence junit [--reports <dir[,dir]>] [--scenario <key>]");
        context.out().println("  dhk bdd evidence report --adapter cucumber|postman|playwright --report <json> --scenario <key>");
        context.out().println("  dhk bdd verify [--feature <key>|--scenario <key>]");
        context.out().println("  dhk bdd coverage [--feature <key>|--scenario <key>]");
        context.out().println("  dhk bdd bind-spec --scenario <key> --change <key> --acceptance <key>");
        context.out().println("  dhk bdd bind-goal --scenario <key> --goal <goal-key>");
        context.out().println("  dhk bdd bind-workflow --scenario <key> --run <workflow-run>");
        context.out().println("  dhk bdd bind-graph --scenario <key> --file <path>|--symbol <symbol>|--sql-table <table>");
        context.out().println("  dhk bdd bind-test --scenario <key> --class <name> [--method <name>]");
        context.out().println("  dhk skill lint --skill <key>|--path <skill-dir>");
        context.out().println("  dhk skill verify --skill <key>|--path <skill-dir>");
        context.out().println("  dhk skill trust --skill <key>|--path <skill-dir>");
        context.out().println("  dhk skill audit --skill <key>|--path <skill-dir>");
        context.out().println("  dhk skill score --goal <goal-key>");
        context.out().println("  dhk skill report --goal <goal-key> [--baseline-score <n>]");
        context.out().println("  dhk skill gate think-before-coding|goal-driven|simplicity|surgical-change --goal <goal-key>");
        context.out().println("  dhk artifact passport verify [--path <path>]");
        context.out().println("  dhk checkpoint request --goal <goal-key> --type <type> --reason <reason>");
        context.out().println("  dhk checkpoint approve --goal <goal-key> --id <id> --approver <name> [--reason <reason>]");
        context.out().println("  dhk checkpoint list --goal <goal-key>");
        context.out().println("  dhk workflow template seed --project-root <path>");
        context.out().println("  dhk workflow template list --project-root <path>");
        context.out().println("  dhk workflow template show --key <workflow>");
        context.out().println("  dhk workflow start --workflow <workflow> --task <task>");
        context.out().println("  dhk workflow status --run <run-key>");
        context.out().println("  dhk workflow phase pass|fail --run <run-key> --phase <phase>");
        context.out().println("  dhk workflow gate pass|fail|waive --run <run-key> [--phase <phase>] --gate <gate>");
        context.out().println("  dhk workflow export --run <run-key>");
        context.out().println("  dhk workflow artifact list --run <run-key>");
        context.out().println("  dhk workflow bind-memory --run <run-key> --memory-id <id>");
        context.out().println("  dhk workflow bind-checkpoint --run <run-key> --checkpoint <id>");
        context.out().println("  dhk workflow summary --run <run-key>");
        context.out().println("  dhk spec create --change <key> --title <title>");
        context.out().println("  dhk spec document set --change <key> --type <type> --content <text>|--content-file <path>|--content-stdin");
        context.out().println("  dhk spec task add|update --change <key> --task <task>");
        context.out().println("  dhk spec acceptance add|update|statuses --change <key> --acceptance <acceptance>");
        context.out().println("  dhk spec status --change <key>");
        context.out().println("  dhk spec export --change <key>");
        context.out().println("  dhk spec bind-workflow --change <key> --run <run-key>");
        context.out().println("  dhk spec archive --change <key> --reason <reason>");
        context.out().println();
        context.out().println("Stability:");
        context.out().println("  Current build: stable 1.0 surface.");
        context.out().println("  Stable surface: help/version/doctor, memory core, goal core, BDD acceptance, configure/status/readiness, release packaging.");
        context.out().println("  Beta surface: DB inspection. SQL guard is not a database permission boundary.");
        context.out().println("  Experimental surface: graph, skill contract/trust, full policy governance, ECC control panel, routine.");
        context.out().println("  See docs/STABLE_CANDIDATE.md and docs/COMPATIBILITY.md.");
        context.out().println();
        context.out().println("Sensitive policy:");
        context.out().println("  .agents/devharness/sensitive-policy.json can set pattern actions to reject, redact, or allow.");
        context.out().println("Goal configuration:");
        context.out().println("  .agents/devharness/config.json records project verification capability presets.");
        context.out().println("  .agents/devharness/goal-profiles/*.json can override or add goal profiles.");
        context.out().println("  .agents/devharness/goal-check-policy.json can configure required goal checks.");
        context.out().println("  .agents/devharness/policy.json can declare stable-candidate local hook policy.");
        context.out().println("Graph configuration:");
        context.out().println("  .agents/graph/config.json controls alpha Graph Lite file scanning.");
        context.out().println("  graph index persists snapshot-bound graph facts to local SQLite.");
        context.out().println("BDD configuration:");
        context.out().println("  .agents/bdd/ stores stable acceptance scenarios and evidence exports.");
        context.out().println("Skill contract configuration:");
        context.out().println("  .agents/skills/<skill-key>/contract.json declares alpha skill governance metadata.");
        context.out().println("Machine-readable output:");
        context.out().println("  Supported commands accept --json; stable command fields are documented.");
        context.out().println("  dhk db sql also supports --format json for query results.");
        context.out().println();
        context.out().println("Exit codes:");
        context.out().println("  0 success");
        context.out().println("  1 runtime error");
        context.out().println("  2 usage error");
        context.out().println("  3 validation or safety rejection");
        context.out().println("  4 target not found");
        return ExitCodes.SUCCESS;
    }
}
